include:
    - path:
        - index/compose.yml
    - path:
        - ledStrip/compose.yml

services:
    alt-routing-framework:
        profiles: [none] 
        build:
            context: .
            dockerfile_inline: FROM sombrepigeon/alt-routing-framework

    alt-routing-demo-old:
        profiles: [dev, prod]
        extends: alt-routing-framework
        build:
            context: old
        environment:
            - VIRTUAL_HOST=old.alt-routing-demo.sombrepigeon.fr
            - LETSENCRYPT_HOST=old.alt-routing-demo.sombrepigeon.fr
        networks:
            proxy:
                aliases: [old.alt-routing-demo.sombrepigeon.fr]
        develop:
            watch:
                -   
                    action: sync
                    path: ./old/src/
                    target: /src/
                    ignore: 
                        - "*.html"
                        - "**/*.html"
                        - "importmap.json"
                -   
                    action: sync+exec
                    path: ./old/src/
                    target: /src/
                    include: 
                        - "*.html"
                        - "**/*.html"
                        - "importmap.json"
                    ignore: 
                        - "index.html"
                        - "**/index.html"
                    exec: 
                        command: make -C /src/ -f /alt-routing-framework/makefile

    alt-routing-demo-basic:
        profiles: [dev, prod]
        extends: alt-routing-framework
        build:
            context: basic
        environment:
            - VIRTUAL_HOST=basic.alt-routing-demo.sombrepigeon.fr
            - LETSENCRYPT_HOST=basic.alt-routing-demo.sombrepigeon.fr
        networks:
            proxy:
                aliases: [basic.alt-routing-demo.sombrepigeon.fr]
        develop:
            watch:
                -   
                    action: sync
                    path: ./basic/src/
                    target: /src/
                    ignore: 
                        - "*.html"
                        - "**/*.html"
                        - "importmap.json"
                -   
                    action: sync+exec
                    path: ./basic/src/
                    target: /src/
                    include: 
                        - "*.html"
                        - "**/*.html"
                        - "importmap.json"
                    ignore: 
                        - "index.html"
                        - "**/index.html"
                    exec: 
                        command: make -C /src/ -f /alt-routing-framework/makefile
                        
    alt-routing-demo-spellbook:
        profiles: [dev, prod]
        extends: alt-routing-framework
        build:
            context: spellbook
        environment:
            - VIRTUAL_HOST=spellbook.alt-routing-demo.sombrepigeon.fr
            - LETSENCRYPT_HOST=spellbook.alt-routing-demo.sombrepigeon.fr
        networks:
            proxy:
                aliases: [spellbook.alt-routing-demo.sombrepigeon.fr]
        develop:
            watch:
                -   
                    action: sync
                    path: ./spellbook/src/
                    target: /src/
                    ignore: 
                        - "*.html"
                        - "**/*.html"
                        - "importmap.json"
                -   
                    action: sync+exec
                    path: ./spellbook/src/
                    target: /src/
                    include: 
                        - "*.html"
                        - "**/*.html"
                        - "importmap.json"
                    ignore: 
                        - "index.html"
                        - "**/index.html"
                    exec: 
                        command: make -C /src/ -f /alt-routing-framework/makefile
