version: '3.7'

services:
    web:
        profiles: [none]
        build: .
        environment:
            - VIRTUAL_HOST=alt-routing-demo.sombrepigeon.fr
            - ENV LETSENCRYPT_HOST=alt-routing-demo.sombrepigeon.fr
        develop:
            watch:
                - 
                    action: sync
                    path: ./src/html
                    target: /usr/local/apache2/htdocs/
        networks:
            nginxproxygitdeploy_net-proxy:
                aliases: [web]

    webprod:
        extends: web
        profiles: [prod]
        environment:
            - VIRTUAL_HOST=alt-routing-demo.sombrepigeon.fr
            - ENV LETSENCRYPT_HOST=alt-routing-demo.sombrepigeon.fr

    webdev:
        extends: web
        profiles: [dev]
        environment:
            - VIRTUAL_HOST=alt-routing-demo.sombrepigeon.fr.localhost
            - ENV LETSENCRYPT_HOST=alt-routing-demo.sombrepigeon.fr.localhost

networks:
    nginxproxygitdeploy_net-proxy:
        external: true
