services:
    alt-routing-demo.base:
        profiles: [none]
        build: 
            context: .
            dockerfile: Containerfile #compatibility :/
        networks:
            proxy:
                aliases: [alt-routing-demo.sombrepigeon.fr]
    alt-routing-demo:
        extends: alt-routing-demo.base
        profiles: [prod]
        environment:
            - VIRTUAL_HOST=alt-routing-demo.sombrepigeon.fr
            - LETSENCRYPT_HOST=alt-routing-demo.sombrepigeon.fr

    alt-routing-demo.dev:
        extends: alt-routing-demo.base
        profiles: [dev]
        environment:
            - VIRTUAL_HOST=alt-routing-demo.sombrepigeon.fr.localhost
            - LETSENCRYPT_HOST=alt-routing-demo.sombrepigeon.fr.localhost
        develop:
            watch:
                -
                    action: rebuild
                    path: ./src/

    alt-routing-demo.firefox:
        image: jlesage/firefox
        profiles: [dev]
        ports: 
            - 5800:5800
        environment:
            - VIRTUAL_HOST=firefox.alt-routing-demo.localhost
            - VIRTUAL_PORT=5800
            - DARK_MODE=1
            - FF_OPEN_URL=alt-routing-demo.sombrepigeon.fr
        configs:
            -   source: alt-routing-demo.firefox.userPref
                target: /config/profile/user.js
        networks:
            proxy:

configs:
    alt-routing-demo.firefox.userPref:
        content: user_pref("dom.securecontext.allowlist", 
                "alt-routing-demo.sombrepigeon.fr,
                alt-routing.dev.releases.sombrepigeon.fr");
            user_pref("devtools.toolbox.host", "right");
            user_pref("devtools.toolbox.previousHost", "right");
