version: '3.7'

services:
    web:
        build: 
            context: .
            target: prod
        volumes:
            - .src/html:/html:ro
            - ./server.js:/server.js:ro
        networks:
            - nginxproxygitdeploy_net-proxy

networks:
    nginxproxygitdeploy_net-proxy:
        external: true