version: '3.7'

services:
    web:
        build: 
            context: .
            target: dev
        volumes:
            - ./src/html:/usr/local/apache2/htdocs/:ro
            #- ./server.js:/server.js:ro
        networks:
            - nginxproxygitdeploy_net-proxy
        #command: node server.js

networks:
    nginxproxygitdeploy_net-proxy:
        external: true